#!/bin/sh

current_branch=$(git symbolic-ref --short HEAD)

if [ "$current_branch" = "prod" ]; then
  # echo "prod 分支"
  echo "prod 需要检查"
  . "$(dirname "$0")/_/husky.sh"

  # Export Git hook params
  export GIT_PARAMS=$*
  npx --no-install fabric verify-commit
fi

# Export Git hook params
export GIT_PARAMS=$*

npx --no-install fabric verify-commit
